title: Fabio Rasera
email: fabiorasera00@gmail.com
description: >- 
  Computational Physicist | Statistical Modelling | Simulations | HPC
baseurl: ""
url: "https://frasera00.github.io"
linkedin_username: frasera00
github_username: frasera00
